# Setup
title:               Peer Production in Citizen Science
tagline:             'Lessons from my PhD'
description:         
url:                 https://katoss.github.io
baseurl:             /peer-production-in-citizen-science/
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Katharina Kloppenborg
  url:               https://github.com/katoss
  email:             katharina.kloppenborg@gmail.com

# Gems
plugins:
  - jekyll-paginate

